#!/usr/bin/env python3
"""make_overrides.py — deterministic passthrough-overrides.json (P3).

The fidelity/contribution DIAL was hand-assembled on acquia; every site gets
the same shape now: demote everything, promote exactly the heuristic roles the
vision segmentation covers (promote-roles.json, written by segment2manifest),
asset refs pointing at the module's static mirror copy.

Usage: make_overrides.py <project> --module <moduleName>
"""
import argparse
import json
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--module", required=True)
    a = ap.parse_args()
    wo = f"projects/{a.project}/workflow-output"
    # TWO ARMS PRODUCE A MANIFEST, ONLY ONE WROTE THIS FILE (2026-08-04). promote-roles
    # comes from segment2manifest, i.e. the VISION arm. A source whose CMS declares its
    # own components skips segmentation entirely (declared2manifest), so the file never
    # exists and this step died three attempts in a row — the adapter-first path was
    # built and this consumer was never taught about it.
    #
    # Defaulting to an empty list would be far worse than failing: demoteRoles is ["*"],
    # promoteRoles is the only thing that wins against it, so an empty set would load
    # EVERY region as verbatim rawHtml and silently erase the whole component model.
    # The declared arm has an exact equivalent — a role here IS the declared component
    # name, the same key extract_content looks up in instanceTypeMap — so the promotable
    # set is every declared type that maps to something other than the passthrough type.
    pr = None
    try:
        pr = json.load(open(f"{wo}/promote-roles.json"))
        source = "promote-roles.json (vision arm)"
    except Exception:                                              # noqa: BLE001
        try:
            man = json.load(open(f"{wo}/component-manifest.json"))
        except Exception:                                          # noqa: BLE001
            sys.exit(f"FAIL: neither {wo}/promote-roles.json (vision arm) nor "
                     f"{wo}/component-manifest.json (declared arm) is readable — "
                     f"nothing can say which roles are modelled, and guessing would "
                     f"demote every region to verbatim rawHtml")
        through = man.get("passthroughType")
        itm = man.get("instanceTypeMap") or {}
        pr = {"promoteRoles": sorted(k for k, v in itm.items() if v and v != through)}
        source = f"component-manifest instanceTypeMap (declared arm, {len(itm)} entries)"
    if not (pr.get("promoteRoles") or []):
        sys.exit(f"FAIL: 0 promotable role(s) from {source} — with demoteRoles ['*'] "
                 f"that loads every region as verbatim rawHtml and erases the model")
    out = {
        "_comment": "Fidelity/contribution dial (QUALITY-PLAN §2/§5, generated by "
                    "make_overrides.py): demoted regions load as verbatim rawHtml "
                    "(with lifted text runs); promoted roles load as skeleton "
                    "instances with per-item decomposition.",
        "demoteRoles": ["*"],
        "chromePassthrough": False,
        "assetBase": f"/modules/{a.module}/static/",
        "promoteRoles": sorted(pr.get("promoteRoles") or []),
    }
    p = f"{wo}/passthrough-overrides.json"
    json.dump(out, open(p, "w"), indent=2, ensure_ascii=False)
    print(f"[make_overrides] {p}: {len(out['promoteRoles'])} promoted role(s) from "
          f"{source}, assetBase={out['assetBase']}")


if __name__ == "__main__":
    main()
