#!/usr/bin/env python3
"""make_overrides.py — deterministic passthrough-overrides.json (P3).

The fidelity/contribution DIAL was hand-assembled on acquia; every site gets
the same shape now: demote everything, promote exactly the heuristic roles the
vision segmentation covers (promote-roles.json, written by segment2manifest),
asset refs pointing at the module's static mirror copy.

Usage: make_overrides.py <project> --module <moduleName>
"""
import argparse
import json
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--module", required=True)
    a = ap.parse_args()
    wo = f"projects/{a.project}/workflow-output"
    try:
        pr = json.load(open(f"{wo}/promote-roles.json"))
    except Exception:
        sys.exit(f"FAIL: {wo}/promote-roles.json missing (run segment2manifest first)")
    out = {
        "_comment": "Fidelity/contribution dial (QUALITY-PLAN §2/§5, generated by "
                    "make_overrides.py): demoted regions load as verbatim rawHtml "
                    "(with lifted text runs); promoted roles load as skeleton "
                    "instances with per-item decomposition.",
        "demoteRoles": ["*"],
        "chromePassthrough": False,
        "assetBase": f"/modules/{a.module}/static/",
        "promoteRoles": sorted(pr.get("promoteRoles") or []),
    }
    p = f"{wo}/passthrough-overrides.json"
    json.dump(out, open(p, "w"), indent=2, ensure_ascii=False)
    print(f"[make_overrides] {p}: {len(out['promoteRoles'])} promoted role(s), "
          f"assetBase={out['assetBase']}")


if __name__ == "__main__":
    main()
