#!/usr/bin/env python3
"""scaffold_cm_views.py — ensure EVERY content type has a `cm` (jContent preview) view.

jContent's back-office editor previews a content node standalone (no page Layout),
so a component with only page-context views appears unstyled/broken there. The
convention: every concrete content type ships a `cm.server.tsx` (name:"cm",
componentType:"view") that renders the node via a shared `CMPreview` wrapper which
loads the module CSS without the header/footer chrome.

This used to be documented for `jmix:mainResource` types only; it now applies to
EVERY content type. This script makes that deterministic (not LLM-dependent):

  1. ensure  src/templates/CMPreview.tsx  — if missing, DERIVE it from the project's
     Layout.tsx CSS cascade (css imports + <AddResources type="css"> lines); minimal
     fallback (dist/assets/style.css) if Layout is absent/unparseable.
  2. for each src/components/<Dir>/ that declares a CONCRETE node type ([ns:type] >)
     and has a *.server.tsx view, write cm.server.tsx if missing:
        - nodeType  <- first concrete [ns:type] in definition.cnd
        - view      <- "fullPage" if fullPage.server.tsx exists, else default
        - display   <- CamelCase dir name, split into words

Idempotent — never overwrites an existing file (so a hand-tuned CMPreview or a
customised cm view is preserved). Gated by components-all.sh.

Usage: python3 orchestration/lib/scaffold_cm_views.py <project_path>
       e.g. python3 orchestration/lib/scaffold_cm_views.py projects/lesalondelaphoto
"""
import os, re, sys, glob


def display_name(dirname):
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", dirname)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", s)
    return s


def concrete_type(cnd_text):
    """First concrete node type ([ns:type] > ...), skipping mixins."""
    m = re.search(r"^\[([a-zA-Z]+:[a-zA-Z0-9]+)\]\s*>", cnd_text, re.M)
    return m.group(1) if m else None


def ensure_cmpreview(proj):
    path = os.path.join(proj, "src/templates/CMPreview.tsx")
    if os.path.exists(path):
        return "exists"
    layout = os.path.join(proj, "src/templates/Layout.tsx")
    css_imports, add_res = [], []
    if os.path.exists(layout):
        txt = open(layout, encoding="utf-8", errors="ignore").read()
        css_imports = re.findall(r'import\s+"([^"]+\.css)"', txt)
        add_res = re.findall(
            r'<AddResources\s+type="css"\s+resources=\{buildModuleFileUrl\("([^"]+)"\)\}', txt
        )
    if not add_res:
        add_res = ["dist/assets/style.css"]
    imports = "\n".join(f'import "{c}";' for c in css_imports)
    ar = "\n".join(
        f'      <AddResources type="css" resources={{buildModuleFileUrl("{r}")}} />' for r in add_res
    )
    content = f'''import {{ AddResources, buildModuleFileUrl }} from "@jahia/javascript-modules-library";
import type {{ ReactNode }} from "react";
{imports}

/**
 * CMPreview — shared wrapper for `cm` views (jContent back-office preview).
 *
 * Loads the module's CSS cascade (mirrored from Layout.tsx) WITHOUT the site
 * header/footer/AbsoluteArea chrome, so a content node previews standalone in the
 * jContent editor panel. Auto-generated by orchestration/lib/scaffold_cm_views.py.
 * Enrich with fonts / Font Awesome remap / :root theme overrides from Layout if the
 * preview needs them.
 */
export const CMPreview = ({{ children }}: {{ children: ReactNode }}) => (
  <>
{ar}
      <main>{{children}}</main>
  </>
);
'''
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write(content)
    return "created"


def cm_view_source(nodetype, disp, has_fullpage):
    view = "fullPage" if has_fullpage else None
    render = (
        f'<Render node={{currentNode as JCRNodeWrapper}} view="{view}" />'
        if view
        else "<Render node={currentNode as JCRNodeWrapper} />"
    )
    base = "fullPage" if view else "default"
    return f'''import {{ jahiaComponent, Render }} from "@jahia/javascript-modules-library";
import type {{ JCRNodeWrapper }} from "org.jahia.services.content";
import {{ CMPreview }} from "../../templates/CMPreview.jsx";

/**
 * `cm` view — standalone preview for the jContent back-office editor panel.
 * Wraps the node's {base} view in CMPreview so it renders with the module's full
 * stylesheet cascade but without the site Layout chrome.
 */
jahiaComponent(
  {{
    componentType: "view",
    nodeType: "{nodetype}",
    name: "cm",
    displayName: "{disp} (jContent Preview)",
  }},
  (_, {{ currentNode }}) => (
    <CMPreview>
      {render}
    </CMPreview>
  ),
);
'''


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: scaffold_cm_views.py <project_path>")
    proj = sys.argv[1].rstrip("/")
    comp_root = os.path.join(proj, "src/components")
    if not os.path.isdir(comp_root):
        sys.exit(f"scaffold_cm_views: no {comp_root}")

    cm_status = ensure_cmpreview(proj)
    print(f"CMPreview.tsx: {cm_status}")

    created, skipped = [], []
    for d in sorted(glob.glob(os.path.join(comp_root, "*/"))):
        cnd = os.path.join(d, "definition.cnd")
        if not os.path.exists(cnd):
            continue
        nt = concrete_type(open(cnd, encoding="utf-8", errors="ignore").read())
        if not nt:
            continue  # mixin-only or no concrete type — not previewable
        if not glob.glob(os.path.join(d, "*.server.tsx")):
            continue  # no view at all — nothing to preview (source-pairing gate covers this)
        out = os.path.join(d, "cm.server.tsx")
        name = os.path.basename(d.rstrip("/"))
        if os.path.exists(out):
            skipped.append(name)
            continue
        has_fullpage = os.path.exists(os.path.join(d, "fullPage.server.tsx"))
        open(out, "w", encoding="utf-8").write(cm_view_source(nt, display_name(name), has_fullpage))
        created.append((name, nt, "fullPage" if has_fullpage else "default"))

    print(f"cm.server.tsx: created {len(created)}, kept {len(skipped)} existing")
    for n, nt, v in created:
        print(f"  + {n:22s} {nt:26s} view={v}")


if __name__ == "__main__":
    main()
